spring.datasource.url=jdbc:mysql://localhost:3306/f1_betting_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
logging.file.name=logs/app.log
logging.level.root=INFO

# OpenF1 API configuration
openf1.api.url=https://api.openf1.org/v1/sessions

